### ISSUE TITLE
StreamJpg error leaves photo tour stuck

### ISSUE THREAD

**Issue by Machriam** [Machriam/PlantMonitor#195]
- For about 1h the photo tour has not proceeded after encountering the following error:
```
[10:36:00 ERR] An unexpected error occurred invoking 'StreamJpg' on the server.
   at System.Threading.Channels.AsyncOperation`1.GetResult(Int16 token)
   at Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.RunChannel[TResult](ChannelReader`1 inputChannel, Channel`1 outputChannel)
   at System.Threading.Channels.AsyncOperation`1.GetResult(Int16 token)
   at Plantmonitor.Server.Features.AutomaticPhotoTour.PictureDiskStreamer.StreamData(String path, CameraTypeInfo cameraInfo, StreamingMetaData data, Func`2 callback, CancellationToken token) in /PlantMonitor/GatewayApp/Backend/Plantmonitor.Server/Features/AutomaticPhotoTour/PictureDiskStreamer.cs:line 68
   at Plantmonitor.Server.Features.AutomaticPhotoTour.PictureDiskStreamer.StartStreamingToDisc(String ip, String deviceId, CameraTypeInfo cameraType, StreamingMetaData data, Action`1 picturePathCallback, Func`2 imageReceivedCallback, CancellationToken token) in /PlantMonitor/GatewayApp/Backend/Plantmonitor.Server/Features/AutomaticPhotoTour/PictureDiskStreamer.cs:line 36
   at Plantmonitor.Shared.Extensions.ObjectExtensions.RunInBackground(Task task, Action`1 exceptionHandler) in /PlantMonitor/GatewayApp/Backend/Plantmonitor.Shared/Extensions/ObjectExtensions.cs:line 9
```

In the future a photo trip with an exception should not halt the photo tour

Events:

Type | Time | Message
-- | -- | --
Debug | 1:32:26 PM | Collected Vis-images: 11, collected Ir-images 31
Debug | 1:32:17 PM | Trying to zero position with Offset: -2000
Information | 1:32:17 PM | Camera working sweet rocket 91. IR checked: True
Information | 1:32:13 PM | Checking Camera sweet rocket 91
Information | 1:32:13 PM | Checking Motor Position sweet rocket 91
Information | 1:32:08 PM | Photo tour resumed
Information | 1:28:39 PM | Photo tour stopped
Error | 1:26:04 PM | Ir streaming error: The operation was canceled.
Debug | 12:36:03 PM | Moving to position: 2000
Debug | 12:36:03 PM | Collected Vis-images: 0, collected Ir-images 14
Error | 12:36:00 PM | Vis streaming error: An unexpected error occurred invoking 'StreamJpg' on the server.
Information | 12:35:58 PM | Camera working sweet rocket 91. IR checked: True
Information | 12:35:51 PM | Checking Camera sweet rocket 91
Information | 12:35:49 PM | Checking Motor Position sweet rocket 91
Information | 12:35:44 PM | Checking Motor Position sweet rocket 91
Information | 12:35:39 PM | Checking Motor Position sweet rocket 91
Information | 12:35:11 PM | eytelia 40 switched sweet rocket 91 on
Information | 12:35:10 PM | american winterberry 44 switched sweet rocket 91 on
Information | 12:35:09 PM | eytelia 40 switched sweet rocket 91 off
Information | 12:35:08 PM | american winterberry 44 switched sweet rocket 91 off

**Comment by Machriam** [comment]
Was never able to replicate this error.
Closing the issue for now.
